//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Background
    {
        public const string BundleName = "background";
        public const string LEVEL1_DOORFRAME = "Level1_Doorframe";
        public const string LEVEL1_GREENWALL = "Level1_GreenWall";
        public const string LEVEL1_ORANGEWALL = "Level1_OrangeWall";
        public const string FURNITURE_L1 = "Furniture_L1";
        public const string L1HOLE_L_L1 = "L1Hole_L_L1";
        public const string L1HOLE_S_L1 = "L1Hole_S_L1";
        public const string WIREHOLE = "WireHole";
        public const string GIANTHOLE = "GiantHole";
        public const string MOSS_ = "moss_";
        public const string SCRATCH = "scratch";
        public const string BACK_L2 = "Back_L2";
        public const string BACKGROUND_LEVEL2 = "Background_Level2";
        public const string T_13 = "T_13";
        public const string T_14 = "T_14";
        public const string T_15 = "T_15";
        public const string T_16 = "T_16";
        public const string T_17 = "T_17";
        public const string T_18 = "T_18";
        public const string T_20 = "T_20";
        public const string T_21 = "T_21";
        public const string T_22 = "T_22";
        public const string L2_FURNITURE = "L2_Furniture";
    }
    public class Background_level1_png
    {
        public const string BundleName = "background_level1_png";
        public const string BACKGROUND_LEVEL1 = "Background_Level1";
    }
    public class Character_1_png
    {
        public const string BundleName = "character_1_png";
        public const string CHARACTER_1 = "Character_1";
    }
    public class Character_2_png
    {
        public const string BundleName = "character_2_png";
        public const string CHARACTER_2 = "Character_2";
    }
    public class Character_3_png
    {
        public const string BundleName = "character_3_png";
        public const string CHARACTER_3 = "Character_3";
    }
    public class Character_4_png
    {
        public const string BundleName = "character_4_png";
        public const string CHARACTER_4 = "Character_4";
    }
    public class Character_5_png
    {
        public const string BundleName = "character_5_png";
        public const string CHARACTER_5 = "Character_5";
    }
    public class Character_6_png
    {
        public const string BundleName = "character_6_png";
        public const string CHARACTER_6 = "Character_6";
    }
    public class Emoji_png
    {
        public const string BundleName = "emoji_png";
        public const string EMOJI = "emoji";
    }
    public class Enemy_prefab
    {
        public const string BundleName = "enemy_prefab";
        public const string ENEMY = "Enemy";
    }
    public class Enemyexit_prefab
    {
        public const string BundleName = "enemyexit_prefab";
        public const string ENEMYEXIT = "EnemyExit";
    }
    public class Enemygenerator_prefab
    {
        public const string BundleName = "enemygenerator_prefab";
        public const string ENEMYGENERATOR = "EnemyGenerator";
    }
    public class Item_prefab
    {
        public const string BundleName = "item_prefab";
        public const string ITEM = "Item";
    }
    public class Trap_prefab
    {
        public const string BundleName = "trap_prefab";
        public const string TRAP = "Trap";
    }
    public class Uicommoneffectpanel_prefab
    {
        public const string BundleName = "uicommoneffectpanel_prefab";
        public const string UICOMMONEFFECTPANEL = "UICommonEffectPanel";
    }
    public class Uiconfirmpanel_prefab
    {
        public const string BundleName = "uiconfirmpanel_prefab";
        public const string UICONFIRMPANEL = "UIConfirmPanel";
    }
    public class Uidamagefloatingtextpanel_prefab
    {
        public const string BundleName = "uidamagefloatingtextpanel_prefab";
        public const string UIDAMAGEFLOATINGTEXTPANEL = "UIDamageFloatingTextPanel";
    }
    public class Uidamagetextcomponent_prefab
    {
        public const string BundleName = "uidamagetextcomponent_prefab";
        public const string UIDAMAGETEXTCOMPONENT = "UIDamageTextComponent";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "UIHomePanel";
    }
    public class Uihudpanel_prefab
    {
        public const string BundleName = "uihudpanel_prefab";
        public const string UIHUDPANEL = "UIHUDPanel";
    }
    public class Uilevelselectionpanel_prefab
    {
        public const string BundleName = "uilevelselectionpanel_prefab";
        public const string UILEVELSELECTIONPANEL = "UILevelSelectionPanel";
    }
    public class Uiloadingpanel_prefab
    {
        public const string BundleName = "uiloadingpanel_prefab";
        public const string UILOADINGPANEL = "UILoadingPanel";
    }
    public class Uimessagetippanel_prefab
    {
        public const string BundleName = "uimessagetippanel_prefab";
        public const string UIMESSAGETIPPANEL = "UIMessageTipPanel";
    }
    public class Uiminimap_prefab
    {
        public const string BundleName = "uiminimap_prefab";
        public const string UIMINIMAP = "UIMiniMap";
    }
    public class Uimousecursorpanel_prefab
    {
        public const string BundleName = "uimousecursorpanel_prefab";
        public const string UIMOUSECURSORPANEL = "UIMouseCursorPanel";
    }
    public class Uipausepanel_prefab
    {
        public const string BundleName = "uipausepanel_prefab";
        public const string UIPAUSEPANEL = "UIPausePanel";
    }
    public class Uiresultpanel_prefab
    {
        public const string BundleName = "uiresultpanel_prefab";
        public const string UIRESULTPANEL = "UIResultPanel";
    }
    public class Uisettingspanel_prefab
    {
        public const string BundleName = "uisettingspanel_prefab";
        public const string UISETTINGSPANEL = "UISettingsPanel";
    }
    public class Uishoppanel_prefab
    {
        public const string BundleName = "uishoppanel_prefab";
        public const string UISHOPPANEL = "UIShopPanel";
    }
}
