//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Uimessagetippanel_prefab
    {
        public const string BundleName = "uimessagetippanel_prefab";
        public const string UIMESSAGETIPPANEL = "UIMessageTipPanel";
    }
    public class Uimousecursorpanel_prefab
    {
        public const string BundleName = "uimousecursorpanel_prefab";
        public const string UIMOUSECURSORPANEL = "UIMouseCursorPanel";
    }
}
